import "./globals.css";

export const metadata = {
  title: "Chilakamarri Srinikethan Nydhruva",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="Du2GIOjLVE9nYhOvSEjEKMBWkBE7lSHW1WSmPOQuOLA"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
